services:
  web:
    build: .
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: _data
    environment:
      # app config
      CHAT_API_DEBUG: ${CHAT_API_DEBUG}
      CHAT_API_APP_HOST: "0.0.0.0"
      CHAT_API_APP_PORT: 5000
      CHAT_API_JWT_SECRET: ${CHAT_API_JWT_SECRET}
      # db config
      CHAT_API_MYSQL_HOST: mysql-db
      CHAT_API_MYSQL_USER: ${CHAT_API_MYSQL_USER}
      CHAT_API_MYSQL_PASSWORD: ${CHAT_API_MYSQL_PASSWORD}
      CHAT_API_MYSQL_DATABASE: ${CHAT_API_MYSQL_DATABASE}
      # active apps
      CHAT_API_USER_ACTIVE: ${CHAT_API_USER_ACTIVE}
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: ${CHAT_API_MYSQL_USER}
      MYSQL_PASSWORD: ${CHAT_API_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CHAT_API_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CHAT_API_MYSQL_DATABASE}
    volumes:
      - ${PWD}/_data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
